import psycopg
from datetime import datetime
from dotenv import load_dotenv
import os
load_dotenv()


def get_connection():
    return psycopg.connect(
        os.getenv("DATABASE_URL")
    )


def create_table():
    conn = get_connection()
    cursor = conn.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS public.list (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
            company_name VARCHAR(255) NOT NULL,
            hr_email VARCHAR(255) NOT NULL,
            date_applied DATE NOT NULL,
            status VARCHAR(100) NOT NULL,
            role VARCHAR(255) NOT NULL,
            website_link VARCHAR(500) NOT NULL
        )
    """)

    conn.commit()
    cursor.close()
    conn.close()


def view_data(User_id):
    conn = get_connection()
    cursor = conn.cursor()

    cursor.execute("""
        SELECT *
        FROM public.list
        WHERE user_id = %s
    """, (User_id,))

    data = cursor.fetchall()

    cursor.close()
    conn.close()

    return data


def add_data(
    User_Id,
    Company_Name,
    HR_Email,
    Role,
    Status,
    Website_link,
    Date_applied=None
):
    conn = get_connection()
    cursor = conn.cursor()

    if not Date_applied:
        Date_applied = datetime.today().date()

    cursor.execute(
        """
        INSERT INTO public.list
        (
            user_id,
            company_name,
            hr_email,
            role,
            status,
            website_link,
            date_applied
        )
        VALUES (%s, %s, %s, %s, %s, %s, %s)
        """,
        (
            User_Id,
            Company_Name,
            HR_Email,
            Role,
            Status,
            Website_link,
            Date_applied
        )
    )

    conn.commit()

    cursor.close()
    conn.close()

def update_status(Status, Id, User_Id):
    conn = get_connection()
    cursor = conn.cursor()

    cursor.execute(
        """
        UPDATE public.list
        SET status = %s
        WHERE id = %s
          AND user_id = %s
        """,
        (Status, Id, User_Id)
    )

    conn.commit()

    cursor.close()
    conn.close()

def delete_data(Id, User_Id):
    conn = get_connection()
    cursor = conn.cursor()

    cursor.execute(
        """
        DELETE FROM public.list
        WHERE id = %s
          AND user_id = %s
        """,
        (Id, User_Id)
    )

    conn.commit()

    cursor.close()
    conn.close()  
# --------------*--------*--------*--------*--------*--------*--------*--------*--------*--------*--------* 
